# Generated by Django 5.2.8 on 2025-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='requiere_geolocalizacion',
            field=models.BooleanField(default=True),
        ),
    ]
