# Generated by Django 4.2.5 on 2025-11-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_sector_requiere_geolocalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_configured', models.BooleanField(default=False)),
            ],
        ),
    ]
